x1unix/go-playground

pkg/analyzer/decl.go
pkg/analyzer/docfmt.go
pkg/analyzer/scanner.go
web/src/editor/provider.ts

* **fix:** add `ParseComments` parser flag
* Provide methods documentation
* Wrap code snippets from GoDoc comments into markdown

Improve code completion

---

Makefile
data/packages.json
pkg/compiler/error.go
pkg/goplay/methods.go
pkg/langserver/errors.go
pkg/langserver/middleware.go
pkg/langserver/request.go
pkg/langserver/server.go
pkg/langserver/spa.go
tools/collector/domCollector.js
web/public/index.html
web/src/editor/props.ts

- Fixes `invalid "format" query parameter value` error when trying to do **Code Format**
- Refactored API server handler
- Added support of Google Analytics via `GTAG` variable

Fix error on code format

---

build/Dockerfile
cmd/playground/main.go
pkg/goplay/client.go
pkg/goplay/client_test.go
pkg/langserver/server.go

Allow to use custom playground URL with `-playground-url` argument, or with `APP_PLAYGROUND_URL` environment variable for Docker image.
Closes #34

#34: Add custom playground URL support

---

build/Dockerfile
web/src/services/go/fs.ts
web/src/services/go/index.ts
web/src/services/go/process.ts
web/src/services/go/wasm_exec.js

Use Go 1.17 and node 17

---

.github/workflows/release.yml

Recently, GitHub Actions [changed a way to declare environment variables](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) which breaks our release process.
This PR fixes this by using a new way to set environment variables.
**Before (broken):**
```yaml
- name: Set release version
run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/v}
```
**New way (correct):**
```yaml
- name: Set release version
run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
```

ci: use new env var syntax

---

cmd/playground/main.go
pkg/compiler/compiler.go
pkg/compiler/env.go
pkg/compiler/env_test.go

Get GOROOT using `go env GOROOT` if value is not defined using environment variables.

server: lookup GOROOT using Go if not defined in environment

---

cmd/playground/main.go
pkg/langserver/spa.go
web/public/404.html

Currently the server don't handle 404 cases and always returns homepage.
This PR adds a proper handling of invalid URLs and returns 404 for unknown paths with a nice 404 page.

Handle 404 not found properly

---

web/src/services/go/snippets.json

Add snippets for [defer](https://gobyexample.com/defer) and [panic+recover](https://gobyexample.com/recover).
Closes #102

web: add snippers for panic, recover and defer

---

build/Dockerfile
cmd/playground/main.go
pkg/goplay/client.go
pkg/langserver/server.go
web/src/components/settings/SettingsModal.tsx
web/src/services/api.ts
web/src/services/config.ts
web/src/store/dispatch.ts

Add support of [gotipplay.golang.org](https://gotipplay.golang.org/) backend for running code using experimental Go versions.
GoTip playground URL can be configured using `-gotip-url` flag or using `APP_GOTIP_URL` environment URL (Docker image only)

Add GoTip playground backend support

---

web/src/components/preview/EvalEventView.tsx
web/src/services/go/snippets.json
web/src/services/go/snippets.ts
web/src/utils/headerutils.ts

Original Go playground supports image output in base64 format (see https://go.dev/play/p/XN6x3L23Vok).
This PR ports similar functionality to the project.

Add images output support

---

web/src/services/go/snippets.json
web/src/services/go/wasm_exec.js

Our playground uses special proxy object to inject/customize global scope of Go's WebAssembly bridge (`wasm_exec.js`) by wrapping `globalThis` with proxy object.
Some `window` calls, like `window.alert` require that execution context object should be `window`.
When proxy object passed instead, occurs an error: 
```
TypeError: 'alert' called on an object that does not implement interface Window
```
Prototype swap by using `setPrototypeOf` also doesn't work.
This PR adds method owner check during method call as a workaround, which replaces proxy object with original `window` during call on any `window` member method (like `alert()`).

WebAssembly: fix execution context for methods that require Window interface 

---

cmd/playground/main.go
web/public/index.html

Add fancy preloader (for slow internet) and `<noscript>` message if JavaScript is disabled.

Add page preloader and noscript message

---

.github/workflows/release.yml

Disable parallel build because it breaks image push process by overwriting `amd64` variant with `arm64`.

Disable parallel build

---

web/src/components/core/Header.css

Currently, on small mobile screens Go logo is displayed not properly and takes a big piece of screen space hiding **Run** button which is very frequently used.
This PR adds logo hide behavior on small screens adding space for *Run* button.
**Before**
**After**

Hide logo on small screens

---

web/package.json
web/src/App.tsx
web/src/components/core/Layout/Layout.css
web/src/components/core/Layout/Layout.tsx
web/src/components/core/Layout/index.ts
web/src/components/core/Panel/PanelAction.css
web/src/components/core/Panel/PanelAction.tsx
web/src/components/core/Panel/PanelHeader.css
web/src/components/core/Panel/PanelHeader.tsx
web/src/components/modals/ChangeLogModal.tsx
web/src/components/pages/Playground.css
web/src/components/pages/Playground.tsx
web/src/components/preview/Preview.css
web/src/components/preview/Preview.tsx
web/src/components/preview/ResizablePreview.css
web/src/components/preview/ResizablePreview.tsx
web/src/components/utils/ConnectedThemeProvider.tsx
web/src/services/config.ts
web/src/store/actions.ts
web/src/store/dispatch.ts
web/src/store/reducers.ts
web/src/store/state.ts
web/src/styles/layout.ts
web/yarn.lock

This PR introduces vertical layout support which can be useful on wide screens.
Also this PR introduces some other useful things as side effect:
- Storing panel height/width in local storage
- Collapse/expand panel in horizontal mode.
Closes #136

Vertical panel support

---

web/src/components/editor/CodeEditor.tsx
web/src/components/editor/commands.ts
web/src/store/reducers.ts

This PR adds 2 new hotkeys to the editor:
* `Shift+Enter` - Insert new line after current line
* `Shift+Ctrl+Enter` - Insert new line before current line
Closes #157

ui: add Shift+Enter and Ctrl+Shift+Enter commands to editor

---

.github/workflows/release.yml
Makefile
build.mk
build/release.dockerfile

Speed-up GitHub Actions workflow by moving front-end build outside.

Speedup build process

---

web/src/plugins/vim/editor.ts

Fixes some issues reported @clouedoc

Fix vim commands behavior

---

build.mk
web/src/components/preview/Preview.tsx

Misc fixed missing in previous MR

Misc fixes

---

internal/langserver/spa.go
web/src/services/gorepl/service.ts
web/src/store/dispatchers/settings.ts
web/src/store/reducers.ts

Serve `X-Raw-Content-Length` for static assets (Wasm binaries mainly) to provide proper progress reports on the UI side when content is served with compression.

Serve raw content length for static assets

---

build.mk
build/Dockerfile
build/release.dockerfile

Strip debug symbols in WASM files

---

web/src/components/modals/Notification/Notification.css
web/src/components/modals/Notification/Notification.tsx
web/src/components/pages/Playground.tsx
web/src/serviceWorkerRegistration.ts
web/src/services/updates.ts
web/src/store/actions/ui.ts
web/src/store/dispatchers/index.ts
web/src/store/dispatchers/updates.ts
web/src/store/notifications/state.ts

Adds check for updates on start and prompts the user to refresh the page if an update is available.
Closes #240

Truncate caches when update is available

---

web/package.json
web/public/examples/wasm/main.go
web/src/components/features/inspector/InspectorPanel/InspectorPanel.tsx
web/src/components/features/inspector/InspectorPanel/index.ts
web/src/components/modals/AboutModal/AboutModal.tsx
web/src/components/pages/PlaygroundPage/PlaygroundPage.tsx
web/src/components/pages/PlaygroundPage/utils.ts
web/src/store/state.ts
web/src/styles/layout.ts
web/yarn.lock

Use relative size in percent for the output panel to keep the aspect ratio during window resizing.
Right now, it is implemented only for vertical layout due to flickering but on resize for horizontal layout.
https://github.com/x1unix/go-playground/assets/9203548/23b80b63-4677-4bfa-bef3-0019750f81e4

Use relative size for panel width

---

build/Dockerfile
build/release.dockerfile

On some browsers, service worker might refuse to do an update if any resource returns 404 during page load.
To prevent this, still provide obsolete JS files explicitly imported by `<script>` or `importScript()` in old version.

fix: provide old assets

---

web/src/pages/index.html

A lot of people use [DarkReader](https://darkreader.org/) browser extension for an automatic dark mode.
Although the playground already supports dark mode, DarkReader still adds it's own dark mode styles and this leads to broken styles on web page.
This PR adds a special meta tag to ask DarkReader to ignore the playground.

fix: disable DarkReader

---

web/src/components/elements/tabs/TabLabel/TabLabel.tsx
web/src/components/features/workspace/Workspace/Workspace.tsx
web/src/components/modals/ConfirmModal/ConfirmContext.tsx
web/src/components/modals/ConfirmModal/ConfirmModal.tsx
web/src/components/modals/ConfirmModal/index.ts
web/src/components/pages/PlaygroundPage/PlaygroundPage.tsx

This PR adds file delete confirmation dialog.
In addition, adds mouse wheel click support to delete a file.

feat: add file delete confirmation

---

Makefile
cmd/playground/main.go
internal/builder/check.go
internal/builder/check_test.go
internal/builder/compiler.go
internal/builder/compiler_test.go
internal/builder/storage/artifact.go
internal/server/handler_v1.go
internal/server/handler_v2.go
internal/server/models.go
pkg/testutil/matchers.go
web/src/components/features/inspector/RunOutput/RunOutput.tsx
web/src/lib/go/wrapper/wrapper.ts
web/src/services/api/models.ts
web/src/services/config/monaco.ts
web/src/services/go/index.ts
web/src/store/dispatchers/build.ts

This PR adds support of Go unit tests compilation.
In order to compile project as unit test, file should nave a `_test.go` prefix (like in regular Go).
In addition, this PR fixes deterministic hash keys for WASM entries.

feat: support WebAssembly unit tests

---

internal/builder/compiler.go
internal/builder/compiler_test.go
internal/builder/detect.go
internal/builder/detect_test.go
internal/server/handler_v2.go
internal/server/models.go
web/src/services/api/models.ts
web/src/services/go/index.ts
web/src/store/dispatchers/build.ts

Pass benchmark (`-test.bench`) and fuzzing (`-test.fuzz`) flags to WASM binary.

feat(wasm): add benchmark support

---

web/src/components/elements/tabs/TabHeader/TabHeader.tsx
web/src/components/elements/tabs/TabLabel/TabLabel.tsx

Fix file tabs navigation issues on touch devices (iPad, phones). Previously tabs switch or close required double tap due to FocusZone trap intercepting any events.
This PR fixes this issue and also makes close button appear always for touch devices as middle click is not available for them. 
https://github.com/user-attachments/assets/7a67f06e-2de2-4e78-a8f3-aa3bb4a20644

fix: fix double-click issue on touch devices

---

README.md

Remove beta URL from README since v2.0 was released today.

chore: remove beta url

---

cmd/playground/main.go
docs/deployment/docker/README.md
docs/deployment/gcloud/README.md
docs/deployment/systemd/README.md
internal/config/config.go
internal/config/config_test.go

This PR bumps default HTTP read and write timeouts + makes them configurable.
This PR address recent often 502 errors caused by slow upstream response.

fix: adjust HTTP response timeout

---

internal/builder/compiler.go

Use standard Go module name if `go.mod` isn't provided for consistent hash keys.

fix: use persistent default go module name

---

web/src/components/elements/misc/Kbd/Kbd.tsx
web/src/components/elements/misc/Kbd/index.ts
web/src/components/features/settings/SettingsModal.tsx
web/src/services/config/config.ts
web/src/store/dispatchers/settings.ts
web/src/store/reducers.ts
web/src/store/state.ts
web/src/store/workspace/config.ts
web/src/store/workspace/dispatchers/files.ts
web/src/store/workspace/dispatchers/snippet.ts
web/src/store/workspace/state.ts
web/src/utils/dom.ts

This PR disables autosave by default as this might be inconvenient for fast prototyping purposes.
Also settings were improved:
* Setting options were reordered to put most important features in the first tab.
* Description for editor font resize with mouse wheel option was improved.
Closes: #400

feat: Refactor settings and make autosave optional

---

web/src/workers/language/language.worker.ts

Add missing TTL for imports cache

fix: add missing cache ttl

---

web/src/services/storage/kv.ts
web/src/workers/language/language.worker.ts

Add workaround for broken cache invalidation in v2.2.0

fix: fix cache invalidation

---

README.md
web/src/components/layout/Header/Header.tsx
web/src/services/storage/kv.ts

Cache server Go versions to avoid calling API and upstream API too often.

feat: cache Go used versions

---

web/src/components/features/settings/SettingsModal.tsx
web/src/components/features/workspace/CodeEditor/CodeEditor.tsx
web/src/services/config/monaco.ts

feat: make tab size configurable

---

web/src/components/features/workspace/CodeEditor/autocomplete/symbols/parse.test.ts
web/src/components/features/workspace/CodeEditor/autocomplete/symbols/parse.ts
web/src/components/features/workspace/CodeEditor/autocomplete/symbols/provider.ts

fix: fix suggestion query

---

web/src/components/features/workspace/CodeEditor/utils/commands.ts
web/src/store/workspace/dispatchers/snippet.ts
web/src/store/workspace/reducers.ts
web/src/store/workspace/state.ts

This PR in addition to a new hotkey, adds some extra precautions before sharing a snippet as:
* Preventing double-sharing of the same unchanged snippet.
* Prevent share when another share is in progress.
* Rate-limit share calls.
Closes #447

feat: Share snippet on Ctrl/Meta+S hotkey

---

internal/server/handler_v1.go

Remove unused and deprecated deprecated in previous release

feat: remove deprecated endpoints

---

web/src/components/features/inspector/Console/Console.tsx
web/src/components/features/inspector/FallbackOutput/FallbackOutput.tsx
web/src/components/features/inspector/FallbackOutput/OutputLine.tsx
web/src/components/features/inspector/FallbackOutput/index.ts
web/src/components/features/inspector/InspectorPanel/InspectorPanel.tsx
web/src/components/features/inspector/RunOutput/RunOutput.tsx
web/src/components/features/settings/SettingsModal.tsx
web/src/store/terminal/types.ts

This PR adds option to disable xterm.js and use a simple HTML output renderer.
Created to address https://github.com/x1unix/go-playground/issues/461

feat: fallback mode without xterm.js

---

web/src/components/features/inspector/FallbackOutput/OutputLine.tsx

Set `white-space: pre-wrap` to wrap text in output

fix: set correct whitespace in output

---

web/src/lib/go/wrapper/wrapper.ts
web/src/workers/go/go.worker.ts

In recent Go versions, Go started using `runtime.wasmWrite` to dump panics and stderr.

feat: support runtime.wasmWrite
