x1unix/go-playground

build.mk

Fixes https://github.com/x1unix/go-playground/issues/69

Fix preinstall script

---

.github/workflows/pull_request.yml
web/.eslintignore
web/.eslintrc.yml
web/package.json
web/src/services/go/foundation.ts
web/src/services/go/go.ts
web/yarn.lock

Adds ESLint to GitHub Actions for pull requests

Web: add ESLint

---

.github/workflows/coverage.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml

* Use cache for jobs
* Use Go 1.17.6 for test and coverage jobs

CI: Add cache and Go 1.17.6 

---

web/package.json
web/src/components/core/Header.tsx
web/src/components/modals/AboutModal.tsx
web/src/components/modals/ChangeLogModal.tsx
web/src/components/utils/SharePopup.tsx
web/src/settings/SettingsModal.tsx
web/src/store/actions.ts
web/src/store/dispatch.ts
web/src/store/reducers.ts
web/src/store/state.ts
web/yarn.lock

Adds a popover notification with shared snippet link.
See: #6

UI: Add share notification

---

web/src/components/modals/ChangeLogModal.tsx

Update changelog for upcoming 1.7 release

web: update changelog

---

web/src/services/go/snippets.json
web/src/services/go/snippets.ts
web/src/utils/headerutils.ts

This PR adds Go generics example.

Add generics example snippet

---

.github/workflows/coverage.yml
.github/workflows/pull_request.yml
build/Dockerfile
web/src/serviceWorkerRegistration.ts
web/src/services/go/snippets.json
web/src/services/go/wasm_exec.js

Go 1.18 support

---

.github/workflows/release.yml

Do build of Docker image for different CPU architectures in parallel using *martix* jobs.

Multiarch parallel Docker image build

---

web/src/components/utils/SharePopup.tsx

Fix invalid snippet URL. Fixes #131

web: fix snippet URL in popup link

---

web/src/index.tsx

Check for updates at service worker start

web: check service-worker for updates

---

web/src/components/core/Header.tsx
web/src/components/modals/AboutModal.tsx
web/src/components/modals/ChangeLogModal.tsx
web/src/components/preview/Preview.tsx
web/src/components/preview/ResizablePreview.tsx
web/src/components/settings/SettingsModal.tsx
web/src/components/utils/ConnectedThemeProvider.tsx
web/src/components/utils/SharePopup.tsx
web/src/components/utils/ThemeableComponent.tsx
web/src/services/config.ts
web/src/store/actions.ts
web/src/store/dispatch.ts
web/src/store/reducers.ts
web/src/store/state.ts
web/src/styles/modal.ts
web/src/utils/theme.ts

Use system color scheme by default for dark mode settings.
Legacy manual toggle can be enabled by disabling **Use System Theme** option.
Closes #149

Follow system dark theme preferences

---

web/src/components/preview/Preview.css

fix(ui): fix word wrap in error alert

---

pkg/goplay/client.go
pkg/goplay/error.go
pkg/goplay/methods.go
pkg/langserver/server.go
web/src/components/core/StatusBar/StatusBar.tsx
web/src/components/preview/Preview.tsx

Fix playground upstream error handler

---

web/src/components/modals/EnvironmentSelectModal/EnvironmentSelectModal.css
web/src/components/modals/EnvironmentSelectModal/EnvironmentSelectModal.tsx

Fix environment selector modal

---

web/src/components/editor/CodeEditor.tsx
web/src/plugins/vim/editor.ts
web/src/store/vim/state.ts

Adds 2 custom Vim commands:
* `:w[rite]` - run snippet
* `:share` - Share snippet
Closes #192

feat: bind ':w' Vim command to run snippet

---

web/src/components/core/StatusBar/StatusBar.tsx
web/src/components/editor/CodeEditor.tsx
web/src/components/editor/utils.ts
web/src/index.tsx
web/src/services/analyzer.ts
web/src/services/config.ts
web/src/store/dispatch.ts

Show warning for time.Now() when using server environment

---

web/src/components/editor/CodeEditor.tsx
web/src/components/editor/provider.ts
web/src/components/editor/utils.ts

Add debouncing for code completion API calls

---

web/src/store/dispatchers/snippets.ts

fix: set loading state after formatting finished

---

web/src/store/dispatchers/build.ts
web/src/utils/duration.ts

fix: properly handle Go execution timeout

---

.github/workflows/issues.yml

Add stale bot

---

web/.eslintrc.cjs
web/package.json
web/src/components/elements/tabs/TabHeader/TabHeader.tsx
web/src/components/elements/tabs/TabLabel/TabLabel.tsx
web/src/components/elements/tabs/TabPanelPlaceholder/TabPanelPlaceholder.tsx
web/src/components/elements/tabs/TabPanelPlaceholder/index.ts
web/src/components/elements/tabs/TabSelector/TabSelector.tsx
web/src/components/elements/tabs/TabSelector/index.ts
web/src/components/elements/tabs/TabView/TabView.tsx
web/src/components/elements/tabs/TabView/debounce.ts
web/src/components/elements/tabs/TabView/styles.ts
web/src/components/elements/tabs/types.ts
web/src/components/features/inspector/InspectorPanel/InspectorPanel.css
web/src/components/features/workspace/FlexContainer/FlexContainer.tsx
web/src/components/features/workspace/Workspace/Workspace.tsx
web/src/components/features/workspace/utils.ts
web/vite.config.ts

Improve the appearance of tabs and implement a compact view for mobile devices.
*Desktop view with overflow support*
*Mobile view*

Improve Tab UI/UX

---

build/Dockerfile
build/release.dockerfile

Fixes `'as' and 'FROM' keywords' casing do not match` message during Docker build

fix: fix FromAsCasting warning

---

internal/server/utils.go

Update unit test issue URL in error message

fix: update unit test issue URL

---

CONTRIBUTING.md
HACKING.md
README.md

Add development guide for contributors

feat: add development guide

---

internal/pkgindex/parser.go
internal/pkgindex/parser_test.go
internal/pkgindex/scanner.go
internal/pkgindex/scanner_test.go

fix: fix generated syscall package description

---

web/src/store/dispatchers/build.ts

This PR fixes stuck progress bar issue caused by redux store update events flood.
This PR caps events with RAF.

fix: cap download progress events

---

web/package.json
web/src/components/features/inspector/Console/Console.css
web/src/components/features/inspector/Console/Console.tsx
web/src/components/modals/Notification/Notification.tsx
web/src/components/modals/Notification/NotificationHost.tsx
web/src/store/notifications/actions.ts
web/src/store/notifications/reducers.ts
web/src/store/notifications/state.ts

Add notifications dismiss transition animations
https://github.com/user-attachments/assets/0f3e8802-1d29-4848-8588-95db44a0bd27

feat: notifications dismiss animations

---

cmd/playground/main.go
docs/deployment/docker/README.md
internal/builder/compiler.go
internal/builder/error.go
internal/config/config.go
internal/config/config_test.go
internal/server/handler_v2.go

* Gracefully handle build timeout errors.
* Expose build timeout config

feat: make build timeout adjustable

---

.github/workflows/release.yml
build.mk

chore: Go 1.23

---

internal/pkgindex/docutil/comments.go
internal/pkgindex/docutil/testdata/builtin/expect.json
internal/pkgindex/imports/parser_test.go
web/src/components/features/workspace/CodeEditor/CodeEditor.module.css
web/src/components/features/workspace/CodeEditor/CodeEditor.tsx
web/src/components/features/workspace/CodeEditor/autocomplete/hover/parse.ts
web/src/components/features/workspace/CodeEditor/autocomplete/parser/tokens.ts
web/src/services/completion/service.ts
web/src/services/completion/utils.ts

Fixed:
* Cursor reset issue on package namespace completion accepted.
* Broken URLs in symbol documentation.
* Cache population on hover didn't work.
* etc.

fix: autocompletion issues

---

.github/workflows/release.yml
build.mk
build/Dockerfile
build/release.dockerfile

Build WASM and JSON files in GH Actions to speed up CI builds

feat: move WASM and JSON file builds from Docker

---

web/src/changelog.json
web/src/components/features/workspace/CodeEditor/CodeEditor.tsx
web/src/components/features/workspace/CodeEditor/autocomplete/register.ts
web/src/components/features/workspace/CodeEditor/grammar/gomod.ts
web/src/components/features/workspace/CodeEditor/grammar/ids.ts
web/src/components/features/workspace/CodeEditor/grammar/index.ts
web/src/components/features/workspace/CodeEditor/grammar/register.ts
web/src/components/features/workspace/CodeEditor/utils/props.ts

Enables experimental syntax highlight for `go.mod` files

feat: basic Go.Mod syntax support

---

web/src/components/features/workspace/CodeEditor/syntaxcheck/checker.ts
web/src/components/features/workspace/CodeEditor/syntaxcheck/time.ts
web/src/workers/analyzer/analyzer.worker.ts
web/src/workers/analyzer/types.ts

Append model version to markers to avoid dangling markers

fix: append model version id to marker

---

web/package.json
web/yarn.lock

Upgrade `@fluentui/react` to fix missing icons error

fix: upgrade @fluentui/react

---

web/src/components/features/examples/ExamplesSection/ExamplesSection.tsx
web/src/components/modals/AboutModal/FooterButtons/FooterButtons.tsx
web/src/components/utils/SharePopup.tsx

Fix stuff that broke after migration

fix: broken styles after @fluentui/react migration
